"""Build a portable browser view of archived results; never invokes a model."""
import json,csv,argparse
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
def build(archive):
    notes=json.loads((archive/'evidence/review-notes.json').read_text())['rows'];reviews={r['id']:r for r in notes if r['experiment']=='full'}
    table=list(csv.DictReader((archive/'review/application.csv').open()));cases=[]
    for row in table:
        identity=row['id'];e=json.loads((archive/f'evidence/full/evidence/{identity}.json').read_text());trace=e['observable_trace'];text='\n\n'.join(c.get('assistant_text') or '' for c in trace['model_calls']).strip()
        if identity=='formal-i10-p':
            plan=json.loads(trace['model_calls'][1]['returned_tool_calls'][0]['canonical_arguments']['plan']);text=plan['stages'][1]['tasks'][0]['description']
        cases.append(dict(id=identity,name=row['name'],track=row['track'],automatic=float(row['automatic_score']),review=float(row['review_score']),note=row['note'],context=e['trigger']['objective'],observed=text,levels=[int(row[f'D{i}']) for i in range(1,8)]))
    data=dict(cases=cases,automatic=json.loads((archive/'automatic/summary.json').read_text()),review=json.loads((archive/'review/summary.json').read_text()))
    html='''<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>学习决策评测 · 实验结果</title><style>
*{box-sizing:border-box}body{margin:0;background:#f6f8f5;color:#21352e;font:17px/1.7 "Noto Sans CJK SC","Noto Sans CJK JP",sans-serif}main{max-width:1280px;margin:auto;padding:30px 48px}header{border-bottom:1px solid #cddbd2;padding-bottom:18px;margin-bottom:20px}h1{font-size:30px;margin:0}h2{font-size:22px;margin:15px 0 8px}p{margin:8px 0}small{color:#52645b}nav{display:flex;gap:12px;margin:20px 0}button,select{font:inherit;padding:8px 16px;background:white;color:inherit;border:1px solid #bbcfc1;border-radius:5px;cursor:pointer}button[aria-selected=true]{background:#246655;color:white}.metrics{display:flex;gap:35px;flex-wrap:wrap;padding:12px 0}.metrics strong{font-size:29px;display:block}.case{background:white;padding:22px 28px;border:1px solid #d6e0d9;border-radius:6px}pre{font-family:inherit;font-size:16px;line-height:1.8;white-space:pre-wrap;overflow-wrap:anywhere;max-height:190px;overflow:auto;background:#f1f5f1;padding:12px}table{width:100%;border-collapse:collapse;font-size:15px}td,th{text-align:left;padding:8px;border-bottom:1px solid #dfe7e0}img{width:100%;max-height:440px;object-fit:contain}a{color:#246655}summary{cursor:pointer}#validity{display:none}.hint{border-left:3px solid #d0a052;padding-left:15px}footer{font-size:13px;margin-top:20px;color:#627269}@media(max-width:650px){main{padding:20px}h1{font-size:24px}select{max-width:100%}.case{padding:15px}table{font-size:12px}.metrics{gap:20px}}
</style><main><header><small>Learning Agent · Hy3 / 个人活动作品</small><h1>学习助手的决策，怎样评价？</h1><p>读取用户条件、实际输出与工具效果，再核对内容、行动与解释。</p></header><nav><button id="app-tab" aria-selected="true">应用结果与案例</button><button id="method-tab" aria-selected="false">评测方法有效性</button></nav><section id="application"><div class="metrics"><div><strong>48</strong>真实应用场景</div><div><strong>46 / 48</strong>逐例复核通过</div><div><strong>14</strong>存在不同程度缺陷</div><div><strong>7</strong>操作性评价维度</div></div><select id="case-picker" aria-label="选择典型案例"></select><article class="case"><h2 id="case-name"></h2><p id="scores"></p><details><summary>用户情境</summary><pre id="context"></pre></details><h2>助手实际输出</h2><pre id="observed"></pre><h2>复核依据</h2><p id="note" class="hint"></p><p id="counterexample"></p><details><summary>七维等级与原始证据</summary><table id="dimensions"></table><p><a id="evidence-link">查看原始公开证据</a></p></details></article></section><section id="validity"><div class="metrics"><div><strong>22 / 24</strong>三档严格排序</div><div><strong>4.56</strong>重复加权分标准差均值</div><div><strong>0 / 8</strong>评分操纵后的误通过</div></div><img src="../../../assets/stage3/discrimination.png" alt="8组三档输出各3次评分"><p>24份构造输出各评分3次。白点为原始评分；统计使用严重度封顶前的加权分。</p><p class="hint">两次排序失败：未经证实的去重验收获满分；缺少下一步的拒绝与优质答复并列。通过结论多数占比均值98.6%，完整七维向量为72.2%。</p><h2>四类应用结果（逐例复核）</h2><table id="tracks"></table><p><a href="automatic/triplets.csv">完整判别结果</a> · <a href="automatic/stability.csv">逐输出波动</a> · <a href="REPRODUCE.md">离线复算</a></p></section><footer>归档结果浏览器 · 2026-09-10 · 自动评分与开发助手AI复核分别保存 · 本页展示已完成实验</footer></main><script>const DATA=__DATA__;
const labels=['事实与内容','目标与需求','行动与时机','约束与控制','结果可用性','适度与副作用','解释与下一步'];const tracks={planning:'学习规划',intervention:'主动介入',assessment:'成果验收',revision:'计划调整'};
const picker=document.querySelector('#case-picker');for(const c of DATA.cases){const o=document.createElement('option');o.value=c.id;o.textContent=tracks[c.track]+' · '+c.name;picker.append(o)}
function show(id){const c=DATA.cases.find(c=>c.id===id);document.querySelector('#case-name').textContent=c.name;document.querySelector('#scores').textContent=`自动评分 ${c.automatic} 分 → 逐例复核 ${c.review} 分（同一份输出）`;for(const k of ['context','observed','note'])document.querySelector('#'+k).textContent=c[k];document.querySelector('#counterexample').textContent=id==='formal-i10-p'?'实际反例：[1,2] 与 [2] 卷积得到 [2,4]；只有与 [1] 卷积才保持原序列。':'';const table=document.querySelector('#dimensions');table.replaceChildren();labels.forEach((label,i)=>{const tr=table.insertRow();tr.insertCell().textContent=label;tr.insertCell().textContent=c.levels[i]+' / 2'});document.querySelector('#evidence-link').href='evidence/full/evidence/'+id+'.json'}picker.value='formal-i10-p';show(picker.value);picker.onchange=()=>show(picker.value);
for(const [tab,other,section,hide] of [['app-tab','method-tab','application','validity'],['method-tab','app-tab','validity','application']])document.getElementById(tab).onclick=()=>{document.getElementById(tab).setAttribute('aria-selected','true');document.getElementById(other).setAttribute('aria-selected','false');document.getElementById(section).style.display='block';document.getElementById(hide).style.display='none';window.scrollTo(0,0)};
const t=document.querySelector('#tracks');for(const r of DATA.review.application.tracks){const tr=t.insertRow();for(const value of [tracks[r.track],r.passed+'通过 / '+r.failed+'未通过',r.mean_score.toFixed(2)+'分'])tr.insertCell().textContent=value}
</script></html>'''
    (archive/'viewer.html').write_text(html.replace('__DATA__',json.dumps(data,ensure_ascii=False).replace('<','\\u003c')))
if __name__=='__main__':
    p=argparse.ArgumentParser(description=__doc__);p.add_argument('--archive',type=Path,default=ROOT/'evaluation/artifacts/decisionbench-study-20260910');build(p.parse_args().archive)
