"""Build the final results viewer from verified tables, without API requests."""
import csv,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
FINAL=ROOT/'evaluation/artifacts/decisionbench-final-method-20260910'
OLD=ROOT/'evaluation/artifacts/decisionbench-study-20260910'
def build():
    refs={r['id']:r for r in csv.DictReader((OLD/'review/application.csv').open())}
    cases=[]
    for r in csv.DictReader((FINAL/'automatic/application-human.csv').open()):
        ep=OLD/f'evidence/full/evidence/{r["id"]}.json';e=json.loads(ep.read_text())
        observed='\n\n'.join(c.get('assistant_text') or '' for c in e['observable_trace']['model_calls']).strip()
        if r['id']=='formal-i10-p':
            plan=json.loads(e['observable_trace']['model_calls'][1]['returned_tool_calls'][0]['canonical_arguments']['plan'])
            observed=plan['stages'][1]['tasks'][0]['description']
        cases.append({**r,'context':e['trigger']['objective'],'observed':observed,'note':refs[r['id']]['note'],'evidence':str(ep.relative_to(ROOT))})
    data={'cases':cases,'summary':json.loads((FINAL/'automatic/summary.json').read_text()),'tracks':json.loads((OLD/'review/summary.json').read_text())['application']['tracks'],'conditions':json.loads((ROOT/'evaluation/artifacts/condition-validation-20260910/automatic/summary.json').read_text())}
    html='''<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><base href="../../../"><title>学习决策评测结果</title><style>
*{box-sizing:border-box}body{margin:0;background:#f7f8fa;color:#283343;font:17px/1.7 "Noto Sans CJK SC","Noto Sans CJK JP",sans-serif}main{max-width:1280px;margin:auto;padding:26px 48px}header{border-bottom:1px solid #d8dee7;padding-bottom:14px}h1{font-size:30px;margin:0;color:#203d63}h2{font-size:21px;margin:12px 0 6px}p{margin:7px 0}small,footer{color:#647185}nav{display:flex;gap:12px;margin:16px 0}button,select{font:inherit;padding:7px 12px;background:white;color:inherit;border:1px solid #c4cfdd;border-radius:5px;cursor:pointer}select{max-width:100%}button[aria-selected=true]{background:#315f91;color:white}.metrics{display:flex;gap:34px;flex-wrap:wrap;padding:8px 0 16px}.metrics strong{font-size:28px;display:block;color:#203d63}.case{background:white;padding:16px 24px;border:1px solid #dce2ea;border-radius:6px}pre{font:15px/1.7 "Noto Sans CJK SC","Noto Sans CJK JP",sans-serif;white-space:pre-wrap;overflow-wrap:anywhere;max-height:155px;overflow:auto;background:#f3f5f8;padding:10px}table{width:100%;border-collapse:collapse;font-size:15px}td,th{text-align:left;padding:6px;border-bottom:1px solid #dce2ea}img{width:100%;max-height:350px;object-fit:contain}a{color:#315f91}summary{cursor:pointer}#validity{display:none}.hint{background:#f3f5f8;padding:10px}footer{font-size:13px;margin-top:18px}@media(max-width:650px){main{padding:18px}h1{font-size:24px}.case{padding:12px}table{font-size:12px}.metrics{gap:15px}button{font-size:15px}}
</style><main><header><small>Learning Agent · Hy3 / 个人活动作品</small><h1>学习决策评测结果</h1><p>以用户要求、助手内容、工具结果和前后状态为证据，评价内容质量与行动效果。</p></header><nav><button id="app-tab" aria-selected="true">应用结果与案例</button><button id="method-tab" aria-selected="false">评测方法有效性</button></nav><section id="application"><div class="metrics"><div><strong>48</strong>真实应用场景</div><div><strong>46 / 48</strong>人工评分达标</div><div><strong>7</strong>评价维度</div><div><strong>116</strong>全部评测输入</div></div><select id="case-picker" aria-label="选择案例"></select><article class="case"><h2 id="case-name"></h2><p id="scores"></p><details><summary>用户情境</summary><pre id="context"></pre></details><h2>助手实际输出</h2><pre id="observed"></pre><h2>人工参考依据</h2><p id="note" class="hint"></p><p id="counterexample"></p><details><summary>七维等级与原始证据</summary><table id="dimensions"></table><p><a id="evidence-link">原始记录：输入、工具调用、结果与状态（JSON）</a></p></details></article></section><section id="validity"><div class="metrics" id="method-metrics"></div><img src="assets/stage3/discrimination.png" alt="8组正常、局部缺陷、严重缺陷输出各评3次的分数分布"><p>8个情境各构造三档输出，每份评3次；严格排序要求正常分数高于局部缺陷，局部缺陷高于严重缺陷。</p><p id="stability" class="hint"></p><h2>正常与严重错误对照</h2><p id="severe"></p><p><span id="condition-result"></span><a href="evaluation/artifacts/condition-validation-20260910/README.md">完整数据与解释</a>；<a href="evaluation/artifacts/condition-insight-20260910/README.md">卷积核验分析</a>。</p><h2>四类应用结果（人工参考）</h2><table id="tracks"></table><p><a href="evaluation/artifacts/decisionbench-final-method-20260910/automatic/cases.csv">全部200次评分</a> · <a href="evaluation/artifacts/decisionbench-final-method-20260910/README.md">数据说明与复算命令</a> · <a href="第三阶段项目与评测报告.html">完整图文报告</a></p></section><footer>同一冻结方法 · 2026-09-10 · 自动分数与人工参考分别保留 · 两位人工独立标注128条参考记录</footer></main><script>const DATA=__DATA__;
const labels=['事实与内容','目标与需求','行动与时机','约束与控制','结果可用性','适度与副作用','解释与下一步'];const tracks={planning:'学习规划',intervention:'主动介入',assessment:'成果验收',revision:'计划调整'};const picker=document.querySelector('#case-picker');
for(const c of DATA.cases){const o=document.createElement('option');o.value=c.id;o.textContent=tracks[c.track]+' · '+c.name;picker.append(o)}
function show(id){const c=DATA.cases.find(c=>c.id===id);document.querySelector('#case-name').textContent=c.name;document.querySelector('#scores').textContent=`同一份输出：自动 ${c.automatic_score} 分 / 人工参考 ${c.human_score} 分`;for(const k of ['context','observed','note'])document.querySelector('#'+k).textContent=c[k];document.querySelector('#counterexample').textContent=id==='formal-i10-p'?'反例：[1,2] 与 [2] 卷积得到 [2,4]；与 [1] 卷积则保持原序列。':'';const t=document.querySelector('#dimensions');t.innerHTML='<thead><tr><th>维度（0–2级）</th><th>自动评分</th><th>人工参考</th></tr></thead>';const body=t.createTBody();labels.forEach((label,i)=>{const tr=body.insertRow();for(const v of [label,c['automatic_D'+(i+1)],c['human_D'+(i+1)]])tr.insertCell().textContent=v});document.querySelector('#evidence-link').href=c.evidence}
picker.value='formal-i10-p';show(picker.value);picker.onchange=()=>show(picker.value);
for(const [tab,other,section,hide] of [['app-tab','method-tab','application','validity'],['method-tab','app-tab','validity','application']])document.getElementById(tab).onclick=()=>{document.getElementById(tab).setAttribute('aria-selected','true');document.getElementById(other).setAttribute('aria-selected','false');document.getElementById(section).style.display='block';document.getElementById(hide).style.display='none';window.scrollTo(0,0)};
const s=DATA.summary,r=s.repetition.quality;for(const [value,label] of [[s.discrimination.strict_raw+' / 24','三档严格排序'],[r.raw_sd.toFixed(2),'重复加权分标准差均值'],[s.parts.adversarial.passed+' / 8','评分操纵后的误通过']]){const d=document.createElement('div'),strong=document.createElement('strong');strong.textContent=value;d.append(strong,label);document.querySelector('#method-metrics').append(d)}
document.querySelector('#stability').textContent=`同一输出重复评分：通过结论多数占比均值 ${(r.outcome_agreement*100).toFixed(1)}%；完整七维等级相同的多数占比均值 ${(r.dimension_vector_agreement*100).toFixed(1)}%。统计与排序均来自同一冻结方法。`;
const c=DATA.conditions;document.querySelector('#condition-result').textContent=`6组条件对照、36次评分：正常${c.normal_passed}/18通过，缺陷${c.defect_failed}/18未通过。`;
const n=s.parts.new_scenarios;document.querySelector('#severe').textContent=`12组正常/严重输出各评3次：正常通过 ${n.good_passed}/${n.good_total}，严重错误识别并判失败 ${n.severe_critical_failed}/${n.severe_total}。`;
const t=document.querySelector('#tracks');t.innerHTML='<thead><tr><th>场景</th><th>通过结论</th><th>均分</th></tr></thead>';for(const r of DATA.tracks){const tr=t.insertRow();for(const value of [tracks[r.track],r.passed+'通过 / '+r.failed+'未通过',r.mean_score.toFixed(2)+'分'])tr.insertCell().textContent=value}
</script></html>'''
    dest=ROOT/'assets/demo/stage3/viewer.html';dest.write_text(html.replace('__DATA__',json.dumps(data,ensure_ascii=False).replace('<','\\u003c')))
if __name__=='__main__':build()
